// <auto-generated />
namespace ArtGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArtGallery_202102261040 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtGallery_202102261040));
        
        string IMigrationMetadata.Id
        {
            get { return "202102261540382_ArtGallery_202102261040"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
