// <auto-generated />
namespace ArtGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ArtGallery_202102251639 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtGallery_202102251639));
        
        string IMigrationMetadata.Id
        {
            get { return "202102252140055_ArtGallery_202102251639"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
